# config/packages/api_platform.yaml
api_platform:
  formats:
    # on ne garde que JSON « classique »
    json:
      mime_types: ['application/json']
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  # … vos autres options (pagination, swagger, etc.)