# config/packages/security.yaml
security:

  password_hashers:
    App\Entity\User: { algorithm: auto }

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    # Dev tools
    dev:
      pattern: ^/api
      security: false

    # 1) JSON-login pour récupérer le JWT
    login:
      pattern:   ^/api/login$
      stateless: true
      json_login:
        check_path:        /api/login
        username_path:     email
        password_path:     password
        success_handler:   lexik_jwt_authentication.handler.authentication_success
        failure_handler:   lexik_jwt_authentication.handler.authentication_failure

    # 2) Firewall JWT pour toutes les autres requêtes /api
    api:
      pattern:   ^/api
      stateless: true
      provider:  app_user_provider
    #w  jwt:       ~

    # 3) Votre « site » classique (form_login, session, etc.)
    main:
      # on ne met **pas** pattern: ^/ ici, ou alors on l’exclut comme ci-dessous
      # pattern: ^/(?!api)   # Symfony 5+ permet les Regex Lookahead
      lazy:      true
      provider:  app_user_provider
      form_login:
        login_path: /login
        check_path: /login
      logout: true

  access_control:
    - { path: ^/api/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api,        roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/admin,      roles: ROLE_ADMIN }
